apiVersion: v1
kind: Secret
metadata:
  name: reflexio-backend-secrets
  namespace: reflexio
type: Opaque
stringData:
  POSTGRES_DB_URL: "postgresql://reflexio:reflexio@postgres.example.com:5432/reflexio"
  REFLEXIO_OPENSEARCH_ENDPOINT: "https://search-domain.us-west-2.es.amazonaws.com"
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  OPENROUTER_API_KEY: ""
  GEMINI_API_KEY: ""
  MINIMAX_API_KEY: ""
  DEEPSEEK_API_KEY: ""
  DASHSCOPE_API_KEY: ""
  ZAI_API_KEY: ""
  MOONSHOT_API_KEY: ""
  XAI_API_KEY: ""
