"""Converter functions for playbook, user playbook, evaluation result, and playbook aggregation domain objects."""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from reflexio.models.api_schema.service_schemas import (
    AgentPlaybook,
    AgentPlaybookSnapshot,
    AgentPlaybookUpdateEntry,
    AgentSuccessEvaluationResult,
    PlaybookAggregationChangeLog,
    UserPlaybook,
)


def agent_playbook_to_data(agent_playbook: AgentPlaybook) -> dict[str, Any]:
    """
    Convert an AgentPlaybook object to data for upserting into Supabase.

    Args:
        agent_playbook: AgentPlaybook object to convert

    Returns:
        Dictionary containing data ready for upsert
    """
    # skip agent_playbook_id as it is auto generated by supabase
    return {
        "playbook_name": agent_playbook.playbook_name,
        "content": agent_playbook.content,
        "trigger": agent_playbook.trigger,
        "rationale": agent_playbook.rationale,
        "blocking_issue": agent_playbook.blocking_issue.model_dump()
        if agent_playbook.blocking_issue
        else None,
        "playbook_status": agent_playbook.playbook_status,
        "agent_version": agent_playbook.agent_version,
        "playbook_metadata": agent_playbook.playbook_metadata,
        "embedding": agent_playbook.embedding,
        "expanded_terms": agent_playbook.expanded_terms,
        "status": agent_playbook.status,
    }


def user_playbook_to_data(user_playbook: UserPlaybook) -> dict[str, Any]:
    """
    Convert a UserPlaybook object to data for upserting into Supabase.

    Args:
        user_playbook: UserPlaybook object to convert

    Returns:
        Dictionary containing data ready for upsert
    """
    # skip id as it is auto generated by supabase
    return {
        "user_id": user_playbook.user_id,
        "playbook_name": user_playbook.playbook_name,
        "created_at": datetime.fromtimestamp(
            user_playbook.created_at, tz=UTC
        ).isoformat(),
        "request_id": user_playbook.request_id,
        "agent_version": user_playbook.agent_version,
        "content": user_playbook.content,
        "trigger": user_playbook.trigger,
        "rationale": user_playbook.rationale,
        "blocking_issue": user_playbook.blocking_issue.model_dump()
        if user_playbook.blocking_issue
        else None,
        "source_interaction_ids": user_playbook.source_interaction_ids or None,
        "status": user_playbook.status,
        "source": user_playbook.source,
        "embedding": user_playbook.embedding,
        "expanded_terms": user_playbook.expanded_terms,
        "source_span": user_playbook.source_span,
        "notes": user_playbook.notes,
        "reader_angle": user_playbook.reader_angle,
    }


def agent_success_evaluation_result_to_data(
    result: AgentSuccessEvaluationResult,
) -> dict[str, Any]:
    """
    Convert an AgentSuccessEvaluationResult object to data for upserting into Supabase.

    Args:
        result: AgentSuccessEvaluationResult object to convert

    Returns:
        Dictionary containing data ready for upsert
    """
    # skip result_id as it is auto generated by supabase
    return {
        "session_id": result.session_id,
        "agent_version": result.agent_version,
        "evaluation_name": result.evaluation_name,
        "is_success": result.is_success,
        "failure_type": result.failure_type,
        "failure_reason": result.failure_reason,
        "regular_vs_shadow": (
            result.regular_vs_shadow.value if result.regular_vs_shadow else None
        ),
        "number_of_correction_per_session": result.number_of_correction_per_session,
        "user_turns_to_resolution": result.user_turns_to_resolution,
        "is_escalated": result.is_escalated,
        "embedding": result.embedding or None,
    }


def playbook_aggregation_change_log_to_data(
    change_log: PlaybookAggregationChangeLog,
) -> dict[str, Any]:
    """Convert a PlaybookAggregationChangeLog to data for upserting into Supabase.

    Args:
        change_log: PlaybookAggregationChangeLog object to convert

    Returns:
        Dictionary containing data ready for upsert
    """
    # skip id as it is auto generated by supabase
    return {
        "created_at": change_log.created_at,
        "playbook_name": change_log.playbook_name,
        "agent_version": change_log.agent_version,
        "run_mode": change_log.run_mode,
        "added_playbooks": [fb.model_dump() for fb in change_log.added_agent_playbooks],
        "removed_playbooks": [
            fb.model_dump() for fb in change_log.removed_agent_playbooks
        ],
        "updated_playbooks": [
            {"before": entry.before.model_dump(), "after": entry.after.model_dump()}
            for entry in change_log.updated_agent_playbooks
        ],
    }


def _normalize_snapshot(fb: dict[str, Any]) -> dict[str, Any]:
    """Convert old-format snapshots with nested structured_data to flat format.

    Old changelog entries stored before the schema flattening may contain a
    ``structured_data`` dict wrapping trigger/rationale/blocking_issue. This
    helper promotes those keys to top-level so ``AgentPlaybookSnapshot(**fb)``
    works with both old and new formats.
    """
    if "structured_data" in fb:
        sd = fb.pop("structured_data") or {}
        fb.setdefault("trigger", sd.get("trigger"))
        fb.setdefault("rationale", sd.get("rationale"))
        fb.setdefault("blocking_issue", sd.get("blocking_issue"))
    return fb


def response_to_playbook_aggregation_change_log(
    item: dict[str, Any],
) -> PlaybookAggregationChangeLog:
    """Convert a response item from Supabase to a PlaybookAggregationChangeLog object.

    Args:
        item: Dictionary containing change log data from Supabase response

    Returns:
        PlaybookAggregationChangeLog object
    """
    return PlaybookAggregationChangeLog(
        id=item["id"],
        created_at=item["created_at"],
        playbook_name=item["playbook_name"],
        agent_version=item["agent_version"],
        run_mode=item["run_mode"],
        added_agent_playbooks=[
            AgentPlaybookSnapshot(**_normalize_snapshot(fb))
            for fb in (item.get("added_playbooks") or [])
        ],
        removed_agent_playbooks=[
            AgentPlaybookSnapshot(**_normalize_snapshot(fb))
            for fb in (item.get("removed_playbooks") or [])
        ],
        updated_agent_playbooks=[
            AgentPlaybookUpdateEntry(
                before=AgentPlaybookSnapshot(**_normalize_snapshot(entry["before"])),
                after=AgentPlaybookSnapshot(**_normalize_snapshot(entry["after"])),
            )
            for entry in (item.get("updated_playbooks") or [])
        ],
    )


def response_list_to_playbook_aggregation_change_logs(
    response_data: list[dict[str, Any]],
) -> list[PlaybookAggregationChangeLog]:
    """Convert a list of response items to PlaybookAggregationChangeLog objects.

    Args:
        response_data: List of dictionaries from Supabase response

    Returns:
        List of PlaybookAggregationChangeLog objects
    """
    return [response_to_playbook_aggregation_change_log(item) for item in response_data]
