CREATE TABLE IF NOT EXISTS "public"."agent_playbook_source_user_playbooks" (
    "agent_playbook_id" bigint NOT NULL REFERENCES "public"."agent_playbooks" ("agent_playbook_id") ON DELETE CASCADE,
    "user_playbook_id" bigint NOT NULL,
    "source_interaction_ids" bigint[] DEFAULT '{}'::bigint[] NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY ("agent_playbook_id", "user_playbook_id")
);

CREATE INDEX IF NOT EXISTS "idx_apsup_agent"
    ON "public"."agent_playbook_source_user_playbooks" ("agent_playbook_id");
CREATE INDEX IF NOT EXISTS "idx_apsup_user"
    ON "public"."agent_playbook_source_user_playbooks" ("user_playbook_id");

CREATE TABLE IF NOT EXISTS "public"."playbook_optimization_jobs" (
    "job_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "target_kind" text NOT NULL,
    "target_id" bigint NOT NULL,
    "status" text DEFAULT 'pending' NOT NULL,
    "best_candidate_id" bigint,
    "successor_target_id" bigint,
    "decision_reason" text DEFAULT '' NOT NULL,
    "metadata_json" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" bigint NOT NULL,
    "updated_at" bigint NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_poj_target"
    ON "public"."playbook_optimization_jobs" ("target_kind", "target_id");
CREATE INDEX IF NOT EXISTS "idx_poj_status"
    ON "public"."playbook_optimization_jobs" ("status");

CREATE TABLE IF NOT EXISTS "public"."playbook_optimization_candidates" (
    "candidate_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "job_id" bigint NOT NULL REFERENCES "public"."playbook_optimization_jobs" ("job_id") ON DELETE CASCADE,
    "candidate_index" integer DEFAULT 0 NOT NULL,
    "content" text NOT NULL,
    "parent_candidate_ids" bigint[] DEFAULT '{}'::bigint[] NOT NULL,
    "aggregate_score" double precision,
    "is_winner" boolean DEFAULT false NOT NULL,
    "created_at" bigint NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_poc_job"
    ON "public"."playbook_optimization_candidates" ("job_id");

CREATE TABLE IF NOT EXISTS "public"."playbook_optimization_evaluations" (
    "evaluation_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "job_id" bigint NOT NULL REFERENCES "public"."playbook_optimization_jobs" ("job_id") ON DELETE CASCADE,
    "candidate_id" bigint NOT NULL REFERENCES "public"."playbook_optimization_candidates" ("candidate_id") ON DELETE CASCADE,
    "target_kind" text NOT NULL,
    "target_id" bigint NOT NULL,
    "scenario_user_playbook_id" bigint,
    "source_interaction_ids" bigint[] DEFAULT '{}'::bigint[] NOT NULL,
    "score" double precision DEFAULT 0.0 NOT NULL,
    "verdict" text DEFAULT 'tie' NOT NULL,
    "likert" integer DEFAULT 0 NOT NULL,
    "rationale" text DEFAULT '' NOT NULL,
    "asi_json" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "incumbent_rollout_json" jsonb DEFAULT '[]'::jsonb NOT NULL,
    "candidate_rollout_json" jsonb DEFAULT '[]'::jsonb NOT NULL,
    "created_at" bigint NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_poe_job"
    ON "public"."playbook_optimization_evaluations" ("job_id");
CREATE INDEX IF NOT EXISTS "idx_poe_candidate"
    ON "public"."playbook_optimization_evaluations" ("candidate_id");

CREATE TABLE IF NOT EXISTS "public"."playbook_optimization_events" (
    "event_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "job_id" bigint NOT NULL REFERENCES "public"."playbook_optimization_jobs" ("job_id") ON DELETE CASCADE,
    "event_type" text NOT NULL,
    "payload_json" jsonb DEFAULT '{}'::jsonb NOT NULL,
    "created_at" bigint NOT NULL
);

CREATE INDEX IF NOT EXISTS "idx_poev_job"
    ON "public"."playbook_optimization_events" ("job_id");

GRANT ALL ON TABLE "public"."agent_playbook_source_user_playbooks" TO "anon";
GRANT ALL ON TABLE "public"."agent_playbook_source_user_playbooks" TO "authenticated";
GRANT ALL ON TABLE "public"."agent_playbook_source_user_playbooks" TO "service_role";
GRANT ALL ON TABLE "public"."playbook_optimization_jobs" TO "anon";
GRANT ALL ON TABLE "public"."playbook_optimization_jobs" TO "authenticated";
GRANT ALL ON TABLE "public"."playbook_optimization_jobs" TO "service_role";
GRANT ALL ON TABLE "public"."playbook_optimization_candidates" TO "anon";
GRANT ALL ON TABLE "public"."playbook_optimization_candidates" TO "authenticated";
GRANT ALL ON TABLE "public"."playbook_optimization_candidates" TO "service_role";
GRANT ALL ON TABLE "public"."playbook_optimization_evaluations" TO "anon";
GRANT ALL ON TABLE "public"."playbook_optimization_evaluations" TO "authenticated";
GRANT ALL ON TABLE "public"."playbook_optimization_evaluations" TO "service_role";
GRANT ALL ON TABLE "public"."playbook_optimization_events" TO "anon";
GRANT ALL ON TABLE "public"."playbook_optimization_events" TO "authenticated";
GRANT ALL ON TABLE "public"."playbook_optimization_events" TO "service_role";

NOTIFY pgrst, 'reload schema';
