-- Upstream SQLite storage added two durable tables that runtime API/dashboard
-- paths now call through the storage contract. Keep native Postgres storage in
-- parity so Docker/Kubernetes deployments do not inherit NotImplementedError.

CREATE TABLE IF NOT EXISTS "public"."stall_state" (
    id integer PRIMARY KEY CHECK (id = 1),
    stalled boolean NOT NULL DEFAULT false,
    reason text,
    stalled_at timestamptz,
    reset_estimate timestamptz,
    notified_in_cc boolean NOT NULL DEFAULT false,
    last_attempt_at timestamptz,
    error_message text
);

INSERT INTO "public"."stall_state" (id, stalled)
VALUES (1, false)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS "public"."shadow_comparison_verdicts" (
    verdict_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interaction_id text NOT NULL,
    session_id text NOT NULL,
    agent_version text NOT NULL,
    reflexio_is_request_1 boolean NOT NULL,
    better_request text NOT NULL CHECK (better_request IN ('1', '2', 'tie')),
    is_significantly_better boolean NOT NULL,
    comparison_reason text,
    judge_prompt_version text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "idx_shadow_verdicts_session"
    ON "public"."shadow_comparison_verdicts" (session_id, agent_version);

CREATE INDEX IF NOT EXISTS "idx_shadow_verdicts_created_at"
    ON "public"."shadow_comparison_verdicts" (created_at);

CREATE INDEX IF NOT EXISTS "idx_shadow_verdicts_prompt_v"
    ON "public"."shadow_comparison_verdicts" (judge_prompt_version);

ALTER TABLE "public"."interactions"
    ADD COLUMN IF NOT EXISTS "citations" jsonb NOT NULL DEFAULT '[]'::jsonb;

CREATE TABLE IF NOT EXISTS "public"."braintrust_connection" (
    org_id text PRIMARY KEY,
    api_key_enc text NOT NULL,
    workspace_id text NOT NULL,
    workspace_name text NOT NULL DEFAULT '',
    project_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
    last_sync_ts bigint,
    last_error text
);

CREATE TABLE IF NOT EXISTS "public"."imported_score" (
    org_id text NOT NULL,
    source text NOT NULL,
    source_run_id text NOT NULL,
    session_id text,
    scorer_name text NOT NULL,
    value double precision NOT NULL,
    ts bigint NOT NULL,
    PRIMARY KEY (org_id, source, source_run_id, scorer_name)
);

CREATE INDEX IF NOT EXISTS "idx_imported_score_session"
    ON "public"."imported_score" (org_id, session_id)
    WHERE session_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS "idx_imported_score_ts"
    ON "public"."imported_score" (org_id, ts);

ALTER TABLE "public"."_agent_runs"
    ALTER COLUMN "extractor_name" DROP NOT NULL;

CREATE INDEX IF NOT EXISTS "idx_agent_runs_binding_current"
    ON "public"."_agent_runs" (org_id, extractor_kind, user_id);
